-- =============================================================================
-- 001_schema.sql  —  SAP HANA Cloud Schema for Product Catalog Manager
-- =============================================================================
-- Run this script in SAP HANA Database Explorer against your HANA Cloud
-- schema before deploying the Node.js backend.
--
-- Execution order matters — do NOT reorder the blocks:
--   1. Tables (leaf tables first, then FK-referencing tables)
--   2. Sequence  (for ProductID generation)
--   3. View      (vw_ProductFull — denormalised read model)
--
-- To run: open SAP HANA Database Explorer, connect to your schema,
--         open an SQL console, paste this file, and press F8 (Run All).
-- =============================================================================


-- =============================================================================
-- 1. TABLES
-- =============================================================================

-- ── Categories ───────────────────────────────────────────────────────────────
CREATE TABLE "Categories" (
    "CategoryID"   INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CategoryName" NVARCHAR(100) NOT NULL,
    "Description"  NVARCHAR(500),
    "IsActive"     BOOLEAN       DEFAULT TRUE,
    CONSTRAINT "UQ_Categories_Name" UNIQUE ("CategoryName")
);

-- ── Suppliers ────────────────────────────────────────────────────────────────
CREATE TABLE "Suppliers" (
    "SupplierID"   INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SupplierName" NVARCHAR(100) NOT NULL,
    "ContactEmail" NVARCHAR(100),
    "Country"      NVARCHAR(50),
    "IsActive"     BOOLEAN       DEFAULT TRUE,
    CONSTRAINT "UQ_Suppliers_Name" UNIQUE ("SupplierName")
);

-- ── Tags ─────────────────────────────────────────────────────────────────────
CREATE TABLE "Tags" (
    "TagID"   INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TagName" NVARCHAR(50) NOT NULL,
    CONSTRAINT "UQ_Tags_Name" UNIQUE ("TagName")
);

-- ── Products ─────────────────────────────────────────────────────────────────
-- Rating and RatingCount are stored on the Products table (denormalised for
-- read performance — not a separate ratings table).
CREATE TABLE "Products" (
    "ProductID"   NVARCHAR(10)   NOT NULL PRIMARY KEY,
    "ProductName" NVARCHAR(100)  NOT NULL,
    "CategoryID"  INTEGER        NOT NULL,
    "SubCategory" NVARCHAR(60),
    "Description" NCLOB,
    "Price"       DECIMAL(10,2)  NOT NULL,
    "Currency"    NCHAR(3)       DEFAULT 'USD',
    "Stock"       INTEGER        DEFAULT 0,
    "Unit"        NVARCHAR(10)   DEFAULT 'EA',
    "Status"      NVARCHAR(20)   DEFAULT 'Active',
    "SupplierID"  INTEGER,
    "Featured"    BOOLEAN        DEFAULT FALSE,
    "Discount"    TINYINT        DEFAULT 0,
    "Weight"      NVARCHAR(30),
    "Dimensions"  NVARCHAR(60),
    "Rating"      DECIMAL(3,1)   DEFAULT 0.0,
    "RatingCount" INTEGER        DEFAULT 0,
    "CreatedAt"   TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    "ModifiedAt"  TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "FK_Products_Category" FOREIGN KEY ("CategoryID")
        REFERENCES "Categories"("CategoryID"),
    CONSTRAINT "FK_Products_Supplier" FOREIGN KEY ("SupplierID")
        REFERENCES "Suppliers"("SupplierID")
);

-- ── ProductTags (junction) ───────────────────────────────────────────────────
-- ON DELETE CASCADE means deleting a product automatically cleans up its tags.
CREATE TABLE "ProductTags" (
    "ProductID" NVARCHAR(10) NOT NULL,
    "TagID"     INTEGER      NOT NULL,
    PRIMARY KEY ("ProductID", "TagID"),
    CONSTRAINT "FK_ProductTags_Product" FOREIGN KEY ("ProductID")
        REFERENCES "Products"("ProductID") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductTags_Tag"     FOREIGN KEY ("TagID")
        REFERENCES "Tags"("TagID")
);


-- =============================================================================
-- 2. INDEXES
-- =============================================================================
-- HANA automatically creates indexes on PRIMARY KEY and UNIQUE constraints.
-- Add explicit indexes for the most frequent filter/sort patterns.

CREATE INDEX "IDX_Products_Status"     ON "Products"("Status");
CREATE INDEX "IDX_Products_CategoryID" ON "Products"("CategoryID");
CREATE INDEX "IDX_Products_Featured"   ON "Products"("Featured");
CREATE INDEX "IDX_Products_Price"      ON "Products"("Price");
CREATE INDEX "IDX_Products_Stock"      ON "Products"("Stock");
CREATE INDEX "IDX_Products_Name"       ON "Products"("ProductName");


-- =============================================================================
-- 3. SEQUENCE  (replaces the SQL Server sp_GetNextProductID stored procedure)
-- =============================================================================
-- The Node.js backend calls:
--   SELECT "ProductIDSeq".NEXTVAL AS "NextVal" FROM DUMMY
-- and formats the result as P001, P002, ... P999, P1000 etc.
--
-- START WITH 1 means the first product created will be P001.
-- If you already have data (e.g. from the seed file), the sequence is reset
-- after the seed script runs — see 002_seed_data.sql for the RESTART command.

CREATE SEQUENCE "ProductIDSeq"
    START WITH 1
    INCREMENT BY 1
    NO MAXVALUE
    NO CYCLE;


-- =============================================================================
-- 4. VIEW  — vw_ProductFull
-- =============================================================================
-- Denormalised read model that joins Products + Categories + Suppliers + Tags.
-- The backend always reads through this view for GET operations, keeping
-- repository queries free of repetitive JOIN boilerplate.
--
-- STRING_AGG is available in SAP HANA Cloud (based on HANA 2.0 SPS05+).
-- Tags are aggregated into a comma-separated string ("TagsCSV") and then
-- split back into a string array by the rowToDto() function in the repository.

-- Tags are pre-aggregated in a subquery so that the outer SELECT has no
-- GROUP BY at all — this avoids HANA error 264 (LOB type in GROUP BY)
-- which would occur because "Description" is NCLOB.
CREATE VIEW "vw_ProductFull" AS
SELECT
    p."ProductID",
    p."ProductName",
    c."CategoryName"                           AS "Category",
    p."SubCategory",
    p."Description",
    p."Price",
    p."Currency",
    p."Stock",
    p."Unit",
    p."Rating",
    p."RatingCount",
    p."Status",
    IFNULL(s."SupplierName", '')               AS "Supplier",
    p."Featured",
    p."Discount",
    p."Weight",
    p."Dimensions",
    p."CreatedAt",
    p."ModifiedAt",
    IFNULL(tg."TagsCSV", '')                   AS "TagsCSV"
FROM        "Products"    p
INNER JOIN  "Categories"  c   ON  p."CategoryID" = c."CategoryID"
LEFT  JOIN  "Suppliers"   s   ON  p."SupplierID" = s."SupplierID"
LEFT  JOIN  (
    SELECT   pt."ProductID",
             STRING_AGG(t."TagName", ',') AS "TagsCSV"
    FROM     "ProductTags" pt
    JOIN     "Tags"        t  ON pt."TagID" = t."TagID"
    GROUP BY pt."ProductID"
)             tg  ON  tg."ProductID" = p."ProductID";
